#ifndef DEVICES_UI_H
#define DEVICES_UI_H

// Runtime logic for the "Devices" screen designed in EEZ Studio: device list,
// pairing banner, role dialog. NOT generated by EEZ (survives "Build").

#include <lvgl.h>

class DeviceRegistry;
class EspNowManager;

// Call once after ui_init() / weather_ui_init()
void devices_ui_init(DeviceRegistry& registry, EspNowManager& espNow, const char* hubMac);

// Call from the main loop (list status, pairing countdown, hub uptime)
void devices_ui_tick();

// Call after DeviceRegistry::onPacket(): routes Outdoor / Indoor readings to the
// weather screen and refreshes the device list.
void devices_ui_on_packet(int deviceIndex);

#endif /* DEVICES_UI_H */
