#ifndef LIGHTS_UI_H
#define LIGHTS_UI_H

// Runtime logic for the "Lights" screen designed in EEZ Studio: three lamp
// buttons driving an ESP-NOW relay board (protocol: docs/espnow-protocol.md).
// NOT generated by EEZ (survives "Build").

class DeviceRegistry;
class EspNowManager;

// Call once after ui_init()
void lights_ui_init(DeviceRegistry& registry, EspNowManager& espNow);

// Call from the main loop (delivery results, online state)
void lights_ui_tick();

// Call after a packet was recorded in the registry
void lights_ui_refresh();

#endif /* LIGHTS_UI_H */
