// Screen navigation: Weather is the home screen, every page has a menu button,
// the Menu screen lists all pages. Not generated by EEZ (survives "Build").

#include "screens.h"
#include "actions.h"

#define NAV_ANIM_MS 150
#define NAV_LIGHTS_RETURN_MS 30000   // Lights opened from home: back home after 30 s without touch

static lv_obj_t *nav_before_menu = NULL;   // where the menu's back button returns to
static lv_timer_t *nav_return_timer = NULL;

static void nav_go(lv_obj_t *screen) {
    if (screen && screen != lv_screen_active()) {
        lv_screen_load_anim(screen, LV_SCR_LOAD_ANIM_FADE_IN, NAV_ANIM_MS, 0, false);
    }
}

void action_open_menu(lv_event_t *e) {
    LV_UNUSED(e);
    nav_before_menu = lv_screen_active();
    nav_go(objects.menu);
}

void action_menu_back(lv_event_t *e) {
    LV_UNUSED(e);
    nav_go(nav_before_menu ? nav_before_menu : objects.main);
}

// Menu tiles: user data = SCREEN_ID_MAIN .. SCREEN_ID_DEVICES
void action_navigate(lv_event_t *e) {
    int id = (int)(intptr_t)lv_event_get_user_data(e);
    lv_obj_t *screens[] = { objects.main, objects.lights, objects.trends, objects.devices };
    if (id >= SCREEN_ID_MAIN && id <= SCREEN_ID_DEVICES) {
        nav_go(screens[id - SCREEN_ID_MAIN]);
    }
}

static void nav_return_timer_cb(lv_timer_t *timer) {
    LV_UNUSED(timer);
    bool on_lights = lv_screen_active() == objects.lights;
    if (on_lights && lv_display_get_inactive_time(NULL) < NAV_LIGHTS_RETURN_MS) return;

    // Back home after inactivity; stop silently if the user went elsewhere
    if (on_lights) nav_go(objects.main);
    lv_timer_delete(nav_return_timer);
    nav_return_timer = NULL;
}

// Any tap on the home (weather) screen, except the menu button
void action_go_lights(lv_event_t *e) {
    LV_UNUSED(e);
    nav_go(objects.lights);
    if (!nav_return_timer) nav_return_timer = lv_timer_create(nav_return_timer_cb, 1000, NULL);
}
