#ifndef WEATHER_UI_H
#define WEATHER_UI_H

// Runtime logic for the weather dashboard designed in EEZ Studio
// (EEZ/gateway DashBord.eez-project). This file is NOT generated by EEZ,
// so it survives "Build" in EEZ Studio. Widgets are reached through the
// identifiers set in the EEZ project (objects.temperature, objects.chart, ...).

#include <lvgl.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Call once after ui_init()
void weather_ui_init(void);

// Call from the main loop (refreshes "x s ago" and link status)
void weather_ui_tick(void);

// Push a new reading from the Outdoor sensor (big card + trend chart)
void weather_ui_set_data(float temperature, float humidity);

// Show the Indoor sensor in the hero card (has_data = false shows "--")
void weather_ui_set_indoor(bool has_data, float temperature, float humidity);

#ifdef __cplusplus
}
#endif

#endif /* WEATHER_UI_H */
